"""
Reporter — generates HTML and JSON reports from packet analysis summary.
"""

import json
import os
import time

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NetSight Report — {run_id}</title>
<style>
  :root {{
    --bg: #0a0f1e; --card: #111827; --border: #1f2937;
    --text: #e2e8f0; --muted: #6b7280; --accent: #3b82f6;
    --green: #10b981; --yellow: #f59e0b; --red: #ef4444;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }}
  h1 {{ font-size: 1.9rem; color: var(--accent); margin-bottom: 0.2rem; }}
  .meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat {{ background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 1rem 1.2rem; text-align: center; }}
  .stat .num {{ font-size: 1.9rem; font-weight: 700; color: var(--accent); }}
  .stat .label {{ font-size: 0.78rem; color: var(--muted); margin-top: 4px; }}
  .section {{ background: var(--card); border: 1px solid var(--border); border-radius: 10px; margin-bottom: 1.5rem; overflow: hidden; }}
  .section-title {{ padding: 0.75rem 1.25rem; background: #0d1525; font-weight: 700; font-size: 0.85rem;
                    text-transform: uppercase; letter-spacing: 0.07em; color: var(--accent); }}
  .proto-row {{ display: flex; align-items: center; padding: 0.5rem 1.25rem; border-top: 1px solid var(--border); }}
  .proto-name {{ width: 90px; font-weight: 600; font-size: 0.85rem; }}
  .bar-bg {{ flex: 1; background: #1f2937; border-radius: 999px; height: 10px; margin: 0 1rem; }}
  .bar {{ height: 10px; border-radius: 999px; background: var(--accent); }}
  .proto-count {{ width: 50px; text-align: right; font-size: 0.85rem; color: var(--muted); }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; }}
  th {{ background: #0d1525; color: var(--muted); padding: 0.5rem 1rem; text-align: left;
        font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 0.5rem 1rem; border-top: 1px solid var(--border); }}
  tr:hover td {{ background: rgba(59,130,246,0.05); }}
  .flag {{ display: inline-block; padding: 1px 7px; border-radius: 999px; font-size: 0.7rem;
           background: rgba(239,68,68,0.15); color: var(--red); font-weight: 600; }}
  footer {{ text-align: center; color: var(--muted); font-size: 0.75rem; margin-top: 2rem; }}
</style>
</head>
<body>
<h1>🔬 NetSight — Packet Analysis Report</h1>
<div class="meta">Run ID: {run_id} &nbsp;|&nbsp; Captured at: {captured_at} &nbsp;|&nbsp; Analysis duration: {duration_s}s</div>

<div class="grid">
  <div class="stat"><div class="num">{total}</div><div class="label">Packets Captured</div></div>
  <div class="stat"><div class="num">{avg_size}</div><div class="label">Avg Size (bytes)</div></div>
  <div class="stat"><div class="num">{total_kb}</div><div class="label">Total KB</div></div>
  <div class="stat"><div class="num">{proto_count}</div><div class="label">Protocols Detected</div></div>
</div>

<div class="section">
  <div class="section-title">Protocol Breakdown</div>
  {protocol_rows}
</div>

<div class="grid" style="grid-template-columns: 1fr 1fr;">
  <div class="section">
    <div class="section-title">Top Source IPs</div>
    <table>
      <thead><tr><th>IP Address</th><th>Packets</th></tr></thead>
      <tbody>{src_ip_rows}</tbody>
    </table>
  </div>
  <div class="section">
    <div class="section-title">Top Destination IPs</div>
    <table>
      <thead><tr><th>IP Address</th><th>Packets</th></tr></thead>
      <tbody>{dst_ip_rows}</tbody>
    </table>
  </div>
</div>

<div class="section">
  <div class="section-title">Packet Details (first 100)</div>
  <table>
    <thead><tr><th>#</th><th>Protocol</th><th>Source IP</th><th>Destination IP</th><th>Src Port</th><th>Dst Port</th><th>Size</th><th>Flags</th></tr></thead>
    <tbody>{packet_rows}</tbody>
  </table>
</div>

<footer>Generated by NetSight &nbsp;|&nbsp; {captured_at}</footer>
</body>
</html>"""


def generate_report(summary: dict, fmt: str = "both", output_dir: str = "reports"):
    os.makedirs(output_dir, exist_ok=True)
    run_id = summary["run_id"]

    if fmt in ("json", "both"):
        path = os.path.join(output_dir, f"netsight_{run_id}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)
        print(f"📄 JSON report → {path}")

    if fmt in ("html", "both"):
        total = summary["total"]
        max_count = max(summary["protocol_counts"].values()) if summary["protocol_counts"] else 1

        # Protocol bars
        proto_rows = ""
        for proto, count in sorted(summary["protocol_counts"].items(), key=lambda x: -x[1]):
            width = round(count / max_count * 100)
            proto_rows += f'<div class="proto-row"><span class="proto-name">{proto}</span><div class="bar-bg"><div class="bar" style="width:{width}%"></div></div><span class="proto-count">{count}</span></div>'

        # IP rows
        src_ip_rows = "".join(f"<tr><td>{ip}</td><td>{c}</td></tr>" for ip, c in summary["top_src_ips"].items())
        dst_ip_rows = "".join(f"<tr><td>{ip}</td><td>{c}</td></tr>" for ip, c in summary["top_dst_ips"].items())

        # Packet rows (first 100)
        packet_rows = ""
        for i, p in enumerate(summary["packet_details"][:100], 1):
            flag_html = f'<span class="flag">{p["flags"]}</span>' if p["flags"] else ""
            packet_rows += f"<tr><td>{i}</td><td>{p['protocol']}</td><td>{p['src_ip']}</td><td>{p['dst_ip']}</td><td>{p['src_port']}</td><td>{p['dst_port']}</td><td>{p['size']}</td><td>{flag_html}</td></tr>"

        html = HTML_TEMPLATE.format(
            run_id        = run_id,
            captured_at   = summary["captured_at"],
            duration_s    = summary["duration_s"],
            total         = total,
            avg_size      = summary["avg_size_bytes"],
            total_kb      = round(summary["total_bytes"] / 1024, 1),
            proto_count   = len(summary["protocol_counts"]),
            protocol_rows = proto_rows,
            src_ip_rows   = src_ip_rows,
            dst_ip_rows   = dst_ip_rows,
            packet_rows   = packet_rows,
        )

        path = os.path.join(output_dir, f"netsight_{run_id}.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"🌐 HTML report → {path}")
